spring.application.name=edumetrics
spring.datasource.url=jdbc:h2:mem:edumetrics;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.cache.redis.cache-null-values=false
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
logging.level.br.edu.iftm=DEBUG
logging.level.org.springframework.cache=TRACE
rate.limiter.max-requisicoes=100
rate.limiter.janela-ms=60000
